import graphlearn.local_substitution_graph_grammar as lsgg 
from graphlearn.local_substitution_graph_grammar import LocalSubstitutionGraphGrammar as LSGG
import graphlearn.lsgg_core_interface_pair as cip

